"""Create policies table

Revision ID: 0c02f263a298
Revises: 
Create Date: 2023-04-23 17:39:00.830980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c02f263a298'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('date_of_purchase', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=True),
    sa.Column('vehicle_segment', sa.String(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('bodily_injury_liability', sa.Integer(), nullable=True),
    sa.Column('personal_injury_protection', sa.Integer(), nullable=True),
    sa.Column('property_damage_liability', sa.Integer(), nullable=True),
    sa.Column('collision', sa.Integer(), nullable=True),
    sa.Column('comprehensive', sa.Integer(), nullable=True),
    sa.Column('customer_gender', sa.String(), nullable=True),
    sa.Column('customer_income_group', sa.String(), nullable=True),
    sa.Column('customer_region', sa.String(), nullable=True),
    sa.Column('customer_marital_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
